// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using SolarOps.Infrastructure.Persistence;

#nullable disable

namespace SolarOps.Migrations.OracleDb.Migrations
{
    [DbContext(typeof(SolarOpsDbContext))]
    partial class SolarOpsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SolarOps.Domain.Assets.Investor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("NVARCHAR2(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CompanyName");

                    b.ToTable("Investors", (string)null);
                });

            modelBuilder.Entity("SolarOps.Domain.Assets.Plant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)");

                    b.Property<decimal>("AnnualDegradationRatePercent")
                        .HasPrecision(5, 3)
                        .HasColumnType("DECIMAL(5,3)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("NVARCHAR2(32)");

                    b.Property<DateTime>("CommissioningDate")
                        .HasColumnType("DATE");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<decimal>("InstalledCapacityKwp")
                        .HasPrecision(12, 3)
                        .HasColumnType("DECIMAL(12,3)");

                    b.Property<string>("InverterModel")
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)");

                    b.Property<Guid>("InvestorId")
                        .HasColumnType("RAW(16)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BOOLEAN");

                    b.Property<DateTime?>("LastProductionDate")
                        .HasColumnType("DATE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)");

                    b.Property<string>("PvModuleModel")
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("NVARCHAR2(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("NVARCHAR2(32)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.HasIndex("InvestorId");

                    b.HasIndex("SiteId");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique();

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("Plants", (string)null);
                });

            modelBuilder.Entity("SolarOps.Domain.Assets.Site", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name");

                    b.ToTable("Sites", (string)null);
                });

            modelBuilder.Entity("SolarOps.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("NVARCHAR2(512)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("NVARCHAR2(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("SolarOps.Domain.Production.DailyYield", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("DATE");

                    b.Property<decimal>("EnergyKwh")
                        .HasPrecision(14, 3)
                        .HasColumnType("DECIMAL(14,3)");

                    b.Property<Guid>("PlantId")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("NVARCHAR2(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.HasIndex("TenantId", "Date");

                    b.HasIndex("TenantId", "PlantId", "Date")
                        .IsUnique();

                    b.ToTable("DailyYields", (string)null);
                });

            modelBuilder.Entity("SolarOps.Domain.Production.ProductionBaseline", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<decimal>("ExpectedKwh")
                        .HasPrecision(14, 2)
                        .HasColumnType("DECIMAL(14,2)");

                    b.Property<int>("Month")
                        .HasColumnType("NUMBER(10)");

                    b.Property<Guid>("PlantId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("NVARCHAR2(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("Year")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.HasIndex("TenantId", "PlantId", "Year", "Month")
                        .IsUnique();

                    b.ToTable("ProductionBaselines", (string)null);
                });

            modelBuilder.Entity("SolarOps.Domain.Tenants.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)");

                    b.Property<decimal>("PerformanceAlertThreshold")
                        .HasPrecision(5, 4)
                        .HasColumnType("DECIMAL(5,4)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Tenants", (string)null);
                });

            modelBuilder.Entity("SolarOps.Domain.WorkOrders.WorkActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("NCLOB");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("WorkOrderId", "CreatedAtUtc");

                    b.ToTable("WorkActivities", (string)null);
                });

            modelBuilder.Entity("SolarOps.Domain.WorkOrders.WorkOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("CorrelationKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("NCLOB");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("DATE");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("NVARCHAR2(32)");

                    b.Property<Guid>("PlantId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("NVARCHAR2(32)");

                    b.Property<string>("Resolution")
                        .HasMaxLength(4000)
                        .HasColumnType("NCLOB");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("NVARCHAR2(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("NVARCHAR2(32)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.HasIndex("TenantId", "CorrelationKey")
                        .IsUnique();

                    b.HasIndex("TenantId", "PlantId");

                    b.HasIndex("TenantId", "Status", "CreatedAtUtc");

                    b.ToTable("WorkOrders", (string)null);
                });

            modelBuilder.Entity("SolarOps.Domain.WorkOrders.WorkOrderAssignment", b =>
                {
                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("WorkOrderId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("WorkOrderAssignments", (string)null);
                });

            modelBuilder.Entity("SolarOps.Infrastructure.Persistence.Outbox.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Consumer")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<DateTime>("ProcessedOnUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("MessageId", "Consumer");

                    b.ToTable("InboxMessages", (string)null);
                });

            modelBuilder.Entity("SolarOps.Infrastructure.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)");

                    b.Property<int>("Attempts")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasMaxLength(1000000)
                        .HasColumnType("NCLOB");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("TraceParent")
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc", "OccurredOnUtc");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("SolarOps.Domain.Assets.Investor", b =>
                {
                    b.HasOne("SolarOps.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SolarOps.Domain.Assets.Plant", b =>
                {
                    b.HasOne("SolarOps.Domain.Assets.Investor", null)
                        .WithMany()
                        .HasForeignKey("InvestorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolarOps.Domain.Assets.Site", null)
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolarOps.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SolarOps.Domain.Assets.Site", b =>
                {
                    b.HasOne("SolarOps.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SolarOps.Domain.Identity.User", b =>
                {
                    b.HasOne("SolarOps.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SolarOps.Domain.Production.DailyYield", b =>
                {
                    b.HasOne("SolarOps.Domain.Assets.Plant", null)
                        .WithMany()
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SolarOps.Domain.Production.ProductionBaseline", b =>
                {
                    b.HasOne("SolarOps.Domain.Assets.Plant", null)
                        .WithMany()
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SolarOps.Domain.WorkOrders.WorkActivity", b =>
                {
                    b.HasOne("SolarOps.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolarOps.Domain.WorkOrders.WorkOrder", null)
                        .WithMany("Activities")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SolarOps.Domain.WorkOrders.WorkOrder", b =>
                {
                    b.HasOne("SolarOps.Domain.Assets.Plant", null)
                        .WithMany()
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SolarOps.Domain.WorkOrders.WorkOrderAssignment", b =>
                {
                    b.HasOne("SolarOps.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolarOps.Domain.WorkOrders.WorkOrder", null)
                        .WithMany("Assignments")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SolarOps.Domain.WorkOrders.WorkOrder", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Assignments");
                });
#pragma warning restore 612, 618
        }
    }
}
