<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\SolarOps.Api\SolarOps.Api.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" />
    <PackageReference Include="Grpc.Net.Client" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
  </ItemGroup>

</Project>
